###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
  "name": "Cristuina Tesla",
  "age": 34,
  "email": "miyeeu@email.com"
}

###
GET http://localhost:9000/api/users HTTP/1.1

###
GET http://localhost:9000/api/users/66db51b44304a1c9c5e3b5cb HTTP/1.1

###
PUT http://localhost:9000/api/users/66db51b44304a1c9c5e3b5cb HTTP/1.1
Content-Type: application/json

{
  "name": "Leonel Messi",
  "age": 43,
  "email": "Goat@email.com"
}

###
DELETE http://localhost:9000/api/users/66db51b44304a1c9c5e3b5cb HTTP/1.1